spring.application.name=userservice

spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

server.port=8081

project.image=images/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.app.jwtExpirationMs=



#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG


# Needed if you are using elastic beanstalk
#server.port=5000
frontend.url=${FRONTEND_URL:http://localhost:5173}
image.base.url=${IMAGE_BASE_URL:http://localhost:8081/images}

